-- App schema v12 - built-in scripture themes.
--
-- GENERATED by scripts/gen-scripture-themes.py. Edit that script and
-- re-run it; hand edits here are lost. The same generator writes readable
-- copies of each theme to docs/examples/scripture-*.theme.json.
--
-- Seeds two scripture themes that show the reference above the passage,
-- and makes the first one the scripture default on FRESH installs only.
--
-- Why fresh installs only: ThemeService::defaultFor falls back to the
-- first built-in of a kind when no default is stored, so an operator who
-- never picked one is still implicitly on Classic Dark. Switching them on
-- update would change what the congregation sees without anyone choosing
-- it. They get the new themes in the Themes tab instead.
--
-- Telling the two apart in SQL: on a fresh install every migration runs in
-- one pass, so V001's built-ins were created moments ago. On an upgrade
-- they are at least as old as the previous launch. A minute of slack
-- covers a slow first run.
--
-- tokens_version is stamped 3 explicitly (see V006 and V011 for why).
-- NOT EXISTS keeps the inserts safe on a DB that somehow already has
-- them, and INSERT OR IGNORE never overwrites a default someone chose.

INSERT INTO themes (kind, name, tokens_json, is_builtin, tokens_version, created_at, updated_at)
SELECT 'scripture', 'Plum & Rose', '{"version":3,"canvas":{"width":1920,"height":1080},"layouts":[{"id":"content","name":"Content","default":true,"nodes":[{"id":"bg","kind":"container","style":{"x":0,"y":0,"width":100,"height":100,"z":0,"opacity":1.0,"backgroundColor":"#110910"},"data":{"layerName":"Background","fill":{"type":"gradient","gradient":{"style":"mesh","colors":["#110910","#571f44","#1a0c18","#391528"],"angle":0,"animate":false}}}},{"id":"reference","kind":"text","style":{"x":9,"y":11,"width":82,"height":7,"z":3,"opacity":1,"color":"#f29cac","fontFamily":"Funnel Sans","fontPixelSize":40,"fontWeight":600,"letterSpacing":5,"lineHeightMultiplier":1.2,"textTransform":"uppercase","textAlign":"left","verticalAlign":"center"},"data":{"layerName":"Reference","linkage":"scriptureRef","autoResize":false}},{"id":"rule","kind":"container","style":{"x":9,"y":20.5,"width":3.75,"height":0.4,"z":2,"opacity":1,"backgroundColor":"#f29cac"},"data":{"layerName":"Accent rule"}},{"id":"verse","kind":"text","style":{"x":9,"y":26,"width":80,"height":64,"z":2,"opacity":1,"color":"#fcf3f5","fontFamily":"Funnel Sans","fontPixelSize":72,"fontWeight":500,"lineHeightMultiplier":1.26,"textAlign":"left","verticalAlign":"start"},"data":{"layerName":"Verse","linkage":"scriptureText","autoResize":true,"maxFontSize":96,"verseNumberColor":"#f29cac"}}]}]}', 1, 3,
       CAST(strftime('%s','now') AS INTEGER) * 1000,
       CAST(strftime('%s','now') AS INTEGER) * 1000
 WHERE NOT EXISTS (SELECT 1 FROM themes
                    WHERE kind = 'scripture' AND is_builtin = 1 AND name = 'Plum & Rose');
INSERT INTO themes (kind, name, tokens_json, is_builtin, tokens_version, created_at, updated_at)
SELECT 'scripture', 'Graphite & Cyan', '{"version":3,"canvas":{"width":1920,"height":1080},"layouts":[{"id":"content","name":"Content","default":true,"nodes":[{"id":"bg","kind":"container","style":{"x":0,"y":0,"width":100,"height":100,"z":0,"opacity":1.0,"backgroundColor":"#0b0c0e"},"data":{"layerName":"Background","fill":{"type":"gradient","gradient":{"style":"mesh","colors":["#0b0c0e","#17343c","#0e1013","#191c24"],"angle":0,"animate":false}}}},{"id":"reference","kind":"text","style":{"x":9,"y":11,"width":82,"height":7,"z":3,"opacity":1,"color":"#3ac8d4","fontFamily":"Funnel Sans","fontPixelSize":40,"fontWeight":600,"letterSpacing":5,"lineHeightMultiplier":1.2,"textTransform":"uppercase","textAlign":"left","verticalAlign":"center"},"data":{"layerName":"Reference","linkage":"scriptureRef","autoResize":false}},{"id":"rule","kind":"container","style":{"x":9,"y":20.5,"width":3.75,"height":0.4,"z":2,"opacity":1,"backgroundColor":"#3ac8d4"},"data":{"layerName":"Accent rule"}},{"id":"verse","kind":"text","style":{"x":9,"y":26,"width":80,"height":64,"z":2,"opacity":1,"color":"#f4f6f8","fontFamily":"Funnel Sans","fontPixelSize":72,"fontWeight":500,"lineHeightMultiplier":1.26,"textAlign":"left","verticalAlign":"start"},"data":{"layerName":"Verse","linkage":"scriptureText","autoResize":true,"maxFontSize":96,"verseNumberColor":"#3ac8d4"}}]}]}', 1, 3,
       CAST(strftime('%s','now') AS INTEGER) * 1000,
       CAST(strftime('%s','now') AS INTEGER) * 1000
 WHERE NOT EXISTS (SELECT 1 FROM themes
                    WHERE kind = 'scripture' AND is_builtin = 1 AND name = 'Graphite & Cyan');

INSERT OR IGNORE INTO kv (key, value)
SELECT 'default_scripture_theme_id', CAST(t.id AS TEXT)
  FROM themes t
 WHERE t.kind = 'scripture' AND t.is_builtin = 1 AND t.name = 'Plum & Rose'
   AND EXISTS (SELECT 1 FROM themes c
                WHERE c.kind = 'scripture' AND c.is_builtin = 1 AND c.name = 'Classic Dark'
                  AND c.created_at >= CAST(strftime('%s','now') AS INTEGER) * 1000 - 60000);
