-- App schema v13 - built-in song themes.
--
-- @readable-by-older-versions
-- Only adds theme rows and a kv default that 0.7.5 already understands.
--
-- GENERATED by scripts/gen-song-themes.py. Edit that script and re-run
-- it; hand edits here are lost. The same generator writes readable copies
-- of each theme to docs/examples/song-*.theme.json.
--
-- Seeds two song themes that pair with the V012 scripture themes, and
-- makes the first one the song default on FRESH installs only, for the
-- same reason V012 does: an operator who never picked a song default is
-- implicitly on Classic Dark, and switching it on update would change
-- what the congregation sees without anyone choosing it. They get the new
-- themes in the Themes tab instead.
--
-- Fresh versus upgrade is told apart the way V012 does it: on a fresh
-- install V001's built-ins were created moments ago.
--
-- tokens_version is stamped 3 explicitly (see V006 and V011 for why).
-- NOT EXISTS keeps the inserts safe on a DB that somehow already has
-- them, and INSERT OR IGNORE never overwrites a default someone chose.

INSERT INTO themes (kind, name, tokens_json, is_builtin, tokens_version, created_at, updated_at)
SELECT 'song', 'Plum & Rose', '{"version":3,"canvas":{"width":1920,"height":1080},"layouts":[{"id":"content","name":"Content","default":true,"nodes":[{"id":"bg","kind":"container","style":{"x":0,"y":0,"width":100,"height":100,"z":0,"opacity":1.0,"backgroundColor":"#110910"},"data":{"layerName":"Background","fill":{"type":"gradient","gradient":{"style":"mesh","colors":["#110910","#571f44","#1a0c18","#391528"],"angle":0,"animate":false}}}},{"id":"lyric","kind":"text","style":{"x":4,"y":12,"width":92,"height":70,"z":2,"opacity":1,"color":"#fcf3f5","fontFamily":"Funnel Sans","fontPixelSize":72,"fontWeight":600,"lineHeightMultiplier":1.22,"letterSpacing":-0.5,"textAlign":"center","verticalAlign":"center","textShadowColor":"#07030a","textShadowOffsetX":0,"textShadowOffsetY":4,"textShadowBlur":18},"data":{"layerName":"Lyric","linkage":"lyric","autoResize":true,"maxFontSize":80}},{"id":"credits","kind":"text","style":{"x":10,"y":88.5,"width":80,"height":6,"z":3,"opacity":1,"color":"#c9a3ad","fontFamily":"Funnel Sans","fontPixelSize":30,"fontWeight":500,"letterSpacing":1,"lineHeightMultiplier":1.2,"textAlign":"center","verticalAlign":"center"},"data":{"layerName":"Credits","linkage":"songCredits","autoResize":true,"maxFontSize":30}}]}]}', 1, 3,
       CAST(strftime('%s','now') AS INTEGER) * 1000,
       CAST(strftime('%s','now') AS INTEGER) * 1000
 WHERE NOT EXISTS (SELECT 1 FROM themes
                    WHERE kind = 'song' AND is_builtin = 1 AND name = 'Plum & Rose');
INSERT INTO themes (kind, name, tokens_json, is_builtin, tokens_version, created_at, updated_at)
SELECT 'song', 'Graphite & Cyan', '{"version":3,"canvas":{"width":1920,"height":1080},"layouts":[{"id":"content","name":"Content","default":true,"nodes":[{"id":"bg","kind":"container","style":{"x":0,"y":0,"width":100,"height":100,"z":0,"opacity":1.0,"backgroundColor":"#0b0c0e"},"data":{"layerName":"Background","fill":{"type":"gradient","gradient":{"style":"mesh","colors":["#0b0c0e","#17343c","#0e1013","#191c24"],"angle":0,"animate":false}}}},{"id":"lyric","kind":"text","style":{"x":4,"y":12,"width":92,"height":70,"z":2,"opacity":1,"color":"#f4f6f8","fontFamily":"Funnel Sans","fontPixelSize":72,"fontWeight":600,"lineHeightMultiplier":1.22,"letterSpacing":-0.5,"textAlign":"center","verticalAlign":"center","textShadowColor":"#030405","textShadowOffsetX":0,"textShadowOffsetY":4,"textShadowBlur":18},"data":{"layerName":"Lyric","linkage":"lyric","autoResize":true,"maxFontSize":80}},{"id":"credits","kind":"text","style":{"x":10,"y":88.5,"width":80,"height":6,"z":3,"opacity":1,"color":"#9fb0b6","fontFamily":"Funnel Sans","fontPixelSize":30,"fontWeight":500,"letterSpacing":1,"lineHeightMultiplier":1.2,"textAlign":"center","verticalAlign":"center"},"data":{"layerName":"Credits","linkage":"songCredits","autoResize":true,"maxFontSize":30}}]}]}', 1, 3,
       CAST(strftime('%s','now') AS INTEGER) * 1000,
       CAST(strftime('%s','now') AS INTEGER) * 1000
 WHERE NOT EXISTS (SELECT 1 FROM themes
                    WHERE kind = 'song' AND is_builtin = 1 AND name = 'Graphite & Cyan');

INSERT OR IGNORE INTO kv (key, value)
SELECT 'default_song_theme_id', CAST(t.id AS TEXT)
  FROM themes t
 WHERE t.kind = 'song' AND t.is_builtin = 1 AND t.name = 'Plum & Rose'
   AND EXISTS (SELECT 1 FROM themes c
                WHERE c.kind = 'song' AND c.is_builtin = 1 AND c.name = 'Classic Dark'
                  AND c.created_at >= CAST(strftime('%s','now') AS INTEGER) * 1000 - 60000);
